apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "joy-generator.fullname" . }}-config
data:
  token: "${{ include "joy-generator.fullname" . }}-config:PLUGIN_TOKEN"
  baseUrl: "http://{{ include "joy-generator.fullname" . }}"
  requestTimeout: "{{ .Values.requestTimeout }}"
