{{- and (required ".Values.secretEnv.values.PLUGIN_TOKEN is required" .Values.secretEnv.values.PLUGIN_TOKEN) "" -}}
{{- and (required ".Values.env.CATALOG_URL is required" .Values.env.CATALOG_URL) "" -}}

{{- $sealedSecret := (eq .Values.secretEnv.type "sealedSecret") -}}

{{- if $sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- else }}
apiVersion: v1
kind: Secret
{{- end }}
metadata:
  name: {{ include "joy-generator.fullname" . }}-config
{{- if $sealedSecret }}
  annotations:
{{ toYaml .Values.sealedSecretAnnotations | indent 4 }}
{{- end }}
{{- if $sealedSecret }}
spec:
  encryptedData:
{{ toYaml .Values.secretEnv.values | indent 4 }}
{{- else }}
stringData:
{{ toYaml .Values.secretEnv.values | indent 2 }}
{{- end }}

---

{{- if .Values.env.GH_APP_ID }}
{{- and (required ".Values.env.GH_APP_INSTALLATION_ID is required" .Values.env.GH_APP_INSTALLATION_ID) "" |  -}}
{{- and (required ".Values.githubAppPrivateKey is required" .Values.githubAppPrivateKey) "" -}}
{{- if $sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- else }}
apiVersion: v1
kind: Secret
{{- end }}
metadata:
  name: {{ include "joy-generator.fullname" . }}-github-app-key
{{- if $sealedSecret }}
  annotations:
{{ toYaml .Values.sealedSecretAnnotations | indent 4 }}
{{- end }}
{{- if $sealedSecret }}
spec:
  encryptedData:
    githubApp.pem: |
{{ .Values.githubAppPrivateKey | indent 6 }}
{{- else }}
stringData:
  githubApp.pem: |
{{ .Values.githubAppPrivateKey | indent 4 }}
{{- end }}
{{- end }}
