{{- if eq .Values.secretType "secret" }}
apiVersion: v1
kind: Secret
{{- else if eq .Values.secretType "sealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- end }}
metadata:
  name: {{ include "joy-generator.fullname" . }}-config
{{- if eq .Values.secretType "secret" }}
stringData:
{{- include "joy-generator.config" . | indent 2 }}
{{- else if eq .Values.secretType "sealedSecret" }}
spec:
  encryptedData:
{{- include "joy-generator.config" . | indent 4 }}
{{- end }}

---
{{- if .Values.applicationConfig.githubApp }}
{{- if eq .Values.secretType "secret" }}
apiVersion: v1
kind: Secret
{{- else if eq .Values.secretType "sealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- end }}
metadata:
  name: {{ include "joy-generator.fullname" . }}-github-app-key
{{- if eq .Values.secretType "secret" }}
stringData:
  githubApp.pem: |
{{ .Values.applicationConfig.githubApp.privateKey | indent 4 }}
{{- else if eq .Values.secretType "sealedSecret" }}
spec:
  encryptedData:
    githubApp.pem: |
{{ .Values.applicationConfig.githubApp.privateKey | indent 6 }}
{{- end }}
{{- end }}
