apiVersion: v1
kind: Secret
metadata:
  name: {{ include "joy-generator.fullname" . }}-config
stringData:
  JOY_REPO_URL: "{{ .Values.applicationConfig.repoUrl }}"
  {{- if .Values.applicationConfig.githubApp }}
  JOY_GITHUB_APP_ID: "{{ .Values.applicationConfig.githubApp.appId }}"
  JOY_GITHUB_APP_INSTALLATION_ID: "{{ .Values.applicationConfig.githubApp.installationId }}"
  {{- else }}
  JOY_GITHUB_TOKEN: "{{ .Values.applicationConfig.githubToken }}"
  {{- end }}
---
{{- if .Values.applicationConfig.githubApp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "joy-generator.fullname" . }}-github-app-key
stringData:
  githubApp.pem: |
{{ .Values.applicationConfig.githubApp.privateKey | indent 4 }}
{{- end }}
