{{- and (required ".Values.env.PLUGIN_TOKEN is required" .Values.env.PLUGIN_TOKEN) "" -}}
{{- if eq .Values.secretType "secret" }}
apiVersion: v1
kind: Secret
{{- else if eq .Values.secretType "sealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- end }}
metadata:
  name: {{ include "joy-generator.fullname" . }}-config
{{- if eq .Values.secretType "sealedSecret" }}
  {{- with .Values.sealedSecretAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
{{- if eq .Values.secretType "secret" }}
stringData:
{{ toYaml .Values.env | indent 2 }}
{{- else if eq .Values.secretType "sealedSecret" }}
spec:
  encryptedData:
{{ toYaml .Values.env | indent 4 }}
{{- end }}

---
{{- if .Values.env.GH_APP_ID }}
{{- and (required ".Values.env.GH_APP_INSTALLATION_ID is required" .Values.env.GH_APP_INSTALLATION_ID) "" |  -}}
{{- if eq .Values.secretType "secret" }}
apiVersion: v1
kind: Secret
{{- else if eq .Values.secretType "sealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{- end }}
metadata:
  name: {{ include "joy-generator.fullname" . }}-github-app-key
{{- if eq .Values.secretType "sealedSecret" }}
  {{- with .Values.sealedSecretAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
{{- if eq .Values.secretType "secret" }}
stringData:
  githubApp.pem: |
{{ required ".Values.githubApp.privateKey key is required" .Values.githubApp.privateKey | indent 4 }}
{{- else if eq .Values.secretType "sealedSecret" }}
spec:
  encryptedData:
    githubApp.pem: |
{{ required " .Values.githubApp.privateKey key is required" .Values.githubApp.privateKey | indent 6 }}
{{- end }}
{{- end }}
