name: Build & Publish

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "chart/Chart.yaml"
      - "CHANGELOG.md"
  pull_request:
    branches: ["master"]

jobs:
  test-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test chart
        uses: silphid/actions/test-chart@v1
        with:
          work-dir: chart
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Setup dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  publish:
    if: github.ref == 'refs/heads/master'
    needs:
      - test-app
      - test-chart
      - build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          fallback-version: 0.0.0
          skip-commit: true
          skip-version-file: true
          git-push: false

      - name: Update appVersion in chart
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.appVersion = "${{ steps.changelog.outputs.version }}"' 'chart/Chart.yaml'

      - name: Commit release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): ${{ steps.changelog.outputs.tag }}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ steps.changelog.outputs.tag }}

      - name: Build and push Docker image
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # TODO: Build and publish chart

      - name: Push changes
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git push origin master --follow-tags

      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ steps.changelog.outputs.tag }}
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ github.token }}
